### ISSUE TITLE
少数派markdown.css

### ISSUE THREAD

**Issue by feng-fu** [feng-fu/code-fragment#6]
```css
.markdown-here-wrapper {
	font-size: 18px;
	color: #333;
	background: #fff;
	font-family: "PingFang SC","Helvetica Neue", Helvetica, Arial, "Microsoft YaHei", "WenQuanYi Micro Hei", "tohoma,sans-serif";
	margin: 0;
	line-height: 1.6;
	background-image: linear-gradient(90deg, rgba(50, 0, 0, 0.05) 3%, rgba(0, 0, 0, 0) 3%), linear-gradient(360deg,rgba(50, 0, 0, 0.05) 3%, rgba(0, 0, 0, 0) 3%);
	background-size: 20px 20px;
	background-position: center center;
}

h1 {
	font-size: 2.2em;
	font-weight: 700;
	line-height: 1.1;
	padding-top: 16px;
	margin-bottom: 1em;
	text-align: center;
	color: #130f13;
}

h2,
h3,
h4,
h5,
h6 {
	line-height: 1.5em;
	margin-top: 2.2em;
	margin-bottom: 1em;
	color: #130f13;
	text-align: center;
}

h2 {
	font-size: 1.3em;
	line-height: 1.4;
}

h3 {
	font-size: 1.2em;
	line-height: 1.4;
}

h4 {
	font-size: 1.1em;
	line-height: 1.4;
}

h5,
h6 {
	font-size: .9em;
}

h5 {
	font-weight: bold;
	text-transform: uppercase;
}

h6 {
	font-weight: normal;
	color: #AAA;
}

img {
	width: 100%;
	border-radius: 5px;
	display: block;
	margin-bottom: 15px;
	height: auto;
}

dl,
ol,
ul {
	margin-top: 12px;
	margin-bottom: 20px;
	padding-left: 4%;
	line-height: 1.8;
	li
}

p {
	margin: 0 0 20px;
	padding: 0 10px;
	line-height: 1.8;
	list-style: circle;
}

a {
	color: #f22f27;
	text-decoration: none;
}

a:hover {
	color: #f55852;
	text-decoration: underline;
}

a:focus {
	outline-offset: -2px;
}

blockquote {
	font-size: .9em;
	font-style: normal;
	padding: 1em;
	margin: 0 0 15px;
	position: relative;
	line-height: 1.8;
	text-indent: 0;
	border: none;
	color: #888;
	background: rgba(224, 224, 224, .2);
	border-left: 6px solid rgba(242, 47, 39, .4);
}

strong,
dfn {
	font-weight: 700;
	color: rgb(0, 122, 170);
}

em,
dfn {
	font-style: italic;
	font-weight: 400;
}

del {
	text-decoration: line-through;
}

pre {
	margin: 0 0 10px;
	font-size: 13px;
	line-height: 1.42857;
	word-break: break-all;
	word-wrap: break-word;
	border-radius: 4px;
	white-space: pre-wrap;
	display: block;
	background: #f8f8f8;
	padding: 10px 20px;
	border: none;
	margin-bottom: 25px;
	color: #666;
	font-family: Courier, sans-serif;
}

code {
	color: #c7254e;
	background-color: #f9f2f4;
	border-radius: 4px;
	font-family: Menlo, Monaco, Consolas, "Courier New", monospace;
	padding: 2px 4px;
	font-size: 90%;
}

p>code {
	color: #c7264e;
	background-color: #f9f2f4;
	font-size: .95em;
	border-radius: 3px;
	-moz-border-radius: 3px;
	-webkit-border-radius: 3px;
}

figure {
	margin: 1em 0;
}

figcaption {
	font-size: 0.75em;
	padding: 0.5em 2em;
	margin-bottom: 2em;
}

figure img {
	margin-bottom: 0px;
}

hr {
	margin-top: 20px;
	margin-bottom: 20px;
	border: 0;
	border-top: 1px solid #eee;
}

ol p,
ul p {
	margin-bottom: 0px;
}

li {
	margin-bottom: 0.75em;
	margin-top: 0.75em;
}

ol#footnotes {
	font-size: 0.95em;
	padding-top: 1em;
	margin-top: 1em;
	margin-left: 0;
	border-top: 1px solid #eaeaea;
	counter-reset: footer-counter;
	list-style: none;
	color: #555;
	padding-left: 5%;
	margin: 20px 0;
}

ol#footnotes li {
	margin-bottom: 10px;
	margin-left: 16px;
	font-weight: 400;
	line-height: 2;
	list-style-type: none;
}

ol#footnotes li:before {
	content: counter(footer-counter) ". ";
	counter-increment: footer-counter;
	font-weight: 800;
	font-size: .95em;
}

@keyframes highfade {
	0% {
		background-color: none;
	}

	20% {
		background-color: yellow;
	}

	100% {
		background-color: none;
	}
}

@-webkit-keyframes highfade {
	0% {
		background-color: none;
	}

	20% {
		background-color: yellow;
	}

	100% {
		background-color: none;
	}
}

a:target,
ol#footnotes li:target,
sup a:target {
	animation-name: highfade;
	animation-duration: 2s;
	animation-iteration-count: 1;
	animation-timing-function: ease-in-out;
	-webkit-animation-name: highfade;
	-webkit-animation-duration: 2s;
	-webkit-animation-iteration-count: 1;
	-webkit-animation-timing-function: ease-in-out;
}

a:target {
	border: 0;
	outline: 0;
}
```
